# Generated by Django 6.0.7 on 2026-07-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('genero', models.CharField(choices=[('NOV', 'Novela'), ('CUE', 'Cuentos'), ('MIS', 'Misterio'), ('ROM', 'Romance'), ('CRI', 'Crimen')], max_length=3)),
                ('formato', models.CharField(choices=[('FIS', 'Libro Físico')], default='FIS', max_length=3)),
                ('editorial', models.CharField(default='Bajo el Volcán', max_length=150)),
                ('precio', models.PositiveIntegerField(help_text='Precio en COP, sin decimales')),
                ('anio', models.PositiveSmallIntegerField()),
                ('idioma', models.CharField(default='Español', max_length=50)),
                ('dimensiones', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('paginas', models.PositiveSmallIntegerField()),
                ('imagen', models.ImageField(upload_to='libros/')),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='libros/hero/')),
                ('etiqueta', models.CharField(blank=True, choices=[('DES', 'Destacado'), ('NUE', 'Nuevo'), ('PRE', 'Preventa')], max_length=3)),
                ('descripcion', models.TextField()),
                ('frase', models.TextField(blank=True, help_text='Cita destacada del libro')),
                ('separador', models.BooleanField(default=False, help_text="Equivale a 'Si'/'No'/'' del JSON original")),
                ('nuevo', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='catalogo.autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-anio', 'titulo'],
            },
        ),
    ]
