# Generated by Django 6.0.7 on 2026-08-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='imagen_hero',
        ),
    ]
