# Generated by Django 6.0.7 on 2026-08-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_libro_imagen_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil de Instagram', null=True),
        ),
    ]
