# Generated by Django 6.0.7 on 2026-07-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='team/')),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['id'],
            },
        ),
    ]
