# Generated by Django 6.0.7 on 2026-07-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha', models.CharField(help_text="Texto libre en origen ('Pronto', fechas sueltas). Migrar a DateField cuando el dato esté normalizado.", max_length=50)),
                ('categoria', models.CharField(choices=[('EVE', 'Evento'), ('PRO', 'Próximas publicaciones'), ('AUT', 'Nuevos autores'), ('FER', 'Feria del libro'), ('PRE', 'Presentación de libros'), ('PRM', 'Premio nacional de novela')], max_length=3)),
                ('enlace_pdf', models.FileField(blank=True, null=True, upload_to='noticias/pdf/')),
                ('mostrar_participantes', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='eventos/')),
                ('titulo', models.CharField(max_length=200)),
                ('libro', models.CharField(blank=True, help_text='Referencia textual al libro mostrado en la foto', max_length=200)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apariciones_galeria', to='catalogo.autor')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='noticias.noticia')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
            },
        ),
    ]
