# Generated by Django 6.0.7 on 2026-08-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_libro_imagen_hero'),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color_css', models.CharField(blank=True, help_text="Nombre de variable CSS o clase para el color del badge (ej. 'bev-gray-1500').", max_length=30)),
            ],
            options={
                'verbose_name': 'Etiqueta de rol',
                'verbose_name_plural': 'Etiquetas de rol',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='mostrar_participantes',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('evento', 'Evento'), ('lanzamiento', 'Lanzamiento'), ('convocatoria', 'Convocatoria'), ('entrevista', 'Entrevista'), ('premio', 'Premio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='enlace_pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/portadas/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name='AlbumGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('libro', models.CharField(blank=True, max_length=200, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='noticias.noticia')),
            ],
            options={
                'verbose_name': 'Álbum de galería',
                'verbose_name_plural': 'Álbumes de galería',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MultimediaGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento')], max_length=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/galeria/imagenes/')),
                ('video_archivo', models.FileField(blank=True, null=True, upload_to='noticias/galeria/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('archivo_documento', models.FileField(blank=True, null=True, upload_to='noticias/galeria/documentos/')),
                ('titulo_o_descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='noticias.albumgaleria')),
            ],
            options={
                'verbose_name': 'Elemento multimedia',
                'verbose_name_plural': 'Elementos multimedia',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.autor')),
                ('etiqueta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.etiquetarol')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'unique_together': {('noticia', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='noticias_participadas', through='noticias.Participacion', to='catalogo.autor'),
        ),
        migrations.DeleteModel(
            name='ImagenGaleria',
        ),
    ]
