# Generated by Django 6.1.1 on 2026-09-08 22:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_etiquetarol_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediagaleria',
            name='archivo_documento',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='noticias/galeria/documentos/'),
        ),
        migrations.AlterField(
            model_name='multimediagaleria',
            name='video_archivo',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='noticias/galeria/videos/'),
        ),
    ]
