# Generated by Django 6.1.1 on 2026-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_multimediagaleria_archivo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
