# Generated by Django 6.1.1 on 2026-09-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
