# Generated by Django 6.1.1 on 2026-09-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_alter_noticia_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(blank=True, default='Sin resumen', max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
        ),
    ]
