# Generated by Django 6.0.7 on 2026-08-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(help_text='Frase principal del recuadro de premio o anuncio.', max_length=255)),
                ('color_fondo', models.CharField(default='#000000', help_text='Código hexadecimal del color de fondo. Ej: #FF5733', max_length=7)),
                ('imagen', models.ImageField(help_text='Imagen obligatoria del anuncio.', upload_to='home/premios/')),
                ('documento_pdf', models.FileField(blank=True, help_text='Archivo PDF opcional adjunto al anuncio.', null=True, upload_to='home/premios/pdf/')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar el anuncio sin borrarlo.')),
            ],
            options={
                'verbose_name': 'Anuncio de Premio',
                'verbose_name_plural': 'Anuncios de Premios',
            },
        ),
        migrations.CreateModel(
            name='FraseEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Mensaje o frase inspiradora de la editorial.')),
                ('autor', models.CharField(blank=True, help_text='Nombre de quién firma la frase. Opcional.', max_length=150, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar la frase sin borrarla.')),
            ],
            options={
                'verbose_name': 'Frase Editorial',
                'verbose_name_plural': 'Frases Editoriales',
            },
        ),
        migrations.CreateModel(
            name='SlideHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_interno', models.CharField(help_text='Solo para identificar el slide en el panel de administración. No se mostrará en la web.', max_length=100)),
                ('imagen_fondo', models.ImageField(help_text='Imagen de fondo obligatoria del slide.', upload_to='home/hero/')),
                ('documento_descarga', models.FileField(blank=True, help_text='Archivo o documento opcional para descarga.', null=True, upload_to='home/hero/documentos/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número que define el orden de aparición en el carrusel. Menor número aparece primero.')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar el slide sin borrarlo.')),
            ],
            options={
                'verbose_name': 'Slide del Carrusel Hero',
                'verbose_name_plural': 'Slides del Carrusel Hero',
                'ordering': ['orden'],
            },
        ),
    ]
