# Generated by Django 6.0.7 on 2026-08-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidehero',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Texto corto opcional sobre la imagen. Ej: Nuevo, Preventa, Evento.', max_length=50, null=True),
        ),
    ]
