# Generated by Django 6.0.7 on 2026-08-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slidehero_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciopremio',
            name='texto_boton_pdf',
            field=models.CharField(default='Mas info aqui:', max_length=50),
        ),
    ]
