# Generated by Django 6.0.7 on 2026-08-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_anunciopremio_texto_boton_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('enlace_url', models.URLField(blank=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='carrusel/pdfs/')),
                ('texto_boton', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner del carrusel',
                'verbose_name_plural': 'Banners del carrusel',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
