# Generated by Django 6.0.7 on 2026-08-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bannercarrusel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnuncioPremio',
        ),
        migrations.AlterField(
            model_name='fraseeditorial',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fraseeditorial',
            name='autor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fraseeditorial',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slidehero',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slidehero',
            name='documento_descarga',
            field=models.FileField(blank=True, null=True, upload_to='home/hero/documentos/'),
        ),
        migrations.AlterField(
            model_name='slidehero',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slidehero',
            name='imagen_fondo',
            field=models.ImageField(upload_to='home/hero/'),
        ),
        migrations.AlterField(
            model_name='slidehero',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slidehero',
            name='titulo_interno',
            field=models.CharField(max_length=100),
        ),
    ]
