# Generated by Django 6.1.1 on 2026-09-08 22:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_premioscarrusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercarrusel',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='carrusel/pdfs/'),
        ),
        migrations.AlterField(
            model_name='premioscarrusel',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='premios_carrusel/pdfs/'),
        ),
        migrations.AlterField(
            model_name='slidehero',
            name='documento_descarga',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='home/hero/documentos/'),
        ),
    ]
