# Generated by Django 6.1.1 on 2026-09-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_bannercarrusel_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercarrusel',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannercarrusel',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='premioscarrusel',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premioscarrusel',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
